#!/usr/bin/env bash
# print Best School 10 times using the while loop.
#   on the 9th iteration print Hi before Best School.

t=0

while [ $t -lt 10 ]
do
  if [ $t -eq 9 ]
  then
    echo "Hi"	
  fi
  echo "Best School"
  (( t++ ))
done
